services:
  postgres:
    image: postgres:16.3
    container_name: ecom-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: ecom
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
