version: "3.8"
services:
  postgres:
    image: postgres:16.3
    container_name: rest_dev
    environment:
      POSTGRES_DB: rest_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/rest/data
      - ../scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
